In [113]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

Database:

In [79]:
data = pd.read_csv('../data/train_ready_for_WS_preprocessed.csv', delimiter=';', header=0)
data

article_id                                              essay  emotion  \
0             67  really read immigrant article drowned make fee...  sadness   
1             86  phone line suicide prevention line election al...  sadness   
2            206  matter heritage able serve country thai herita...  neutral   
3            290  frightening learn shark attack surfer aware ri...     fear   
4            342  generation russian arent treated properly sort...  sadness   
...          ...                                                ...      ...   
1855          16  day woman winning sport many instance men spor...      joy   
1856         158  hate isi group full hate insanity reason thing...    anger   
1857         203  disgusting can not believe happening people pe...  disgust   
1858         253  feel like world corrupt longer make feel anyth...  sadness   
1859         344  weird experience many people dying enough safe...  sadness   

                                                 tokens  \
0     ['really', 'read', 'immigrant', 'article', 'dr...   
1     ['phone', 'line', 'suicide', 'prevention', 'li...   
2     ['matter', 'heritage', 'able', 'serve', 'count...   
3     ['frightening', 'learn', 'shark', 'attack', 's...   
4     ['generation', 'russian', 'arent', 'treated', ...   
...                                                 ...   
1855  ['day', 'woman', 'winning', 'sport', 'many', '...   
1856  ['hate', 'isi', 'group', 'full', 'hate', 'insa...   
1857  ['disgusting', 'can', 'not', 'believe', 'happe...   
1858  ['feel', 'like', 'world', 'corrupt', 'longer',...   
1859  ['weird', 'experience', 'many', 'people', 'dyi...   

                                                 1-gram  \
0     ['really', 'read', 'immigrant', 'article', 'dr...   
1     ['phone', 'line', 'suicide', 'prevention', 'li...   
2     ['matter', 'heritage', 'able', 'serve', 'count...   
3     ['frightening', 'learn', 'shark', 'attack', 's...   
4     ['generation', 'russian', 'arent', 'treated', ...   
...                                                 ...   
1855  ['day', 'woman', 'winning', 'sport', 'many', '...   
1856  ['hate', 'isi', 'group', 'full', 'hate', 'insa...   
1857  ['disgusting', 'can', 'not', 'believe', 'happe...   
1858  ['feel', 'like', 'world', 'corrupt', 'longer',...   
1859  ['weird', 'experience', 'many', 'people', 'dyi...   

                                                 2-gram  
0     ['really read', 'read immigrant', 'immigrant a...  
1     ['phone line', 'line suicide', 'suicide preven...  
2     ['matter heritage', 'heritage able', 'able ser...  
3     ['frightening learn', 'learn shark', 'shark at...  
4     ['generation russian', 'russian arent', 'arent...  
...                                                 ...  
1855  ['day woman', 'woman winning', 'winning sport'...  
1856  ['hate isi', 'isi group', 'group full', 'full ...  
1857  ['disgusting can', 'can not', 'not believe', '...  
1858  ['feel like', 'like world', 'world corrupt', '...  
1859  ['weird experience', 'experience many', 'many ...  

[1860 rows x 6 columns]

TF-IDF

There are multiple ways to calculate the TF(term frequency)

IDF - inverse document frequency
- looks ar common/uncommon words - corrects for words like as, of, the etc
- minimize the weighting of frequent terms while making infrequent terms have a higher impact.


And then I discovered that you can do all these using TfidfVectorizer that basically does everything you need

In [81]:
gram1data = data['1-gram']

gram1data

0       ['really', 'read', 'immigrant', 'article', 'dr...
1       ['phone', 'line', 'suicide', 'prevention', 'li...
2       ['matter', 'heritage', 'able', 'serve', 'count...
3       ['frightening', 'learn', 'shark', 'attack', 's...
4       ['generation', 'russian', 'arent', 'treated', ...
                              ...                        
1855    ['day', 'woman', 'winning', 'sport', 'many', '...
1856    ['hate', 'isi', 'group', 'full', 'hate', 'insa...
1857    ['disgusting', 'can', 'not', 'believe', 'happe...
1858    ['feel', 'like', 'world', 'corrupt', 'longer',...
1859    ['weird', 'experience', 'many', 'people', 'dyi...
Name: 1-gram, Length: 1860, dtype: object

In [82]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(gram1data)

result

<1860x4607 sparse matrix of type '<class 'numpy.float64'>'
	with 60121 stored elements in Compressed Sparse Row format>

In [83]:
feature_names = tfidf.get_feature_names_out()

print('\nIDF values:')
for ele1, ele2 in zip(feature_names, tfidf.idf_):
    print(ele1, ':', ele2)


IDF values:
abducted : 7.835722076082305
ability : 6.043962606854251
abject : 7.430256967974141
able : 4.086218000151934
abolishing : 7.430256967974141
abortion : 6.91943134420815
absolute : 7.430256967974141
absolutely : 5.270772718620769
absurd : 7.430256967974141
absurdity : 7.430256967974141
abuse : 5.5331369830882595
abused : 6.043962606854251
abuser : 7.14257489552236
abusing : 6.91943134420815
academic : 7.430256967974141
academy : 7.430256967974141
accept : 6.13097398384388
acceptable : 6.226284163648205
accepted : 6.449427714962415
accepting : 6.91943134420815
access : 5.484346818918827
accessible : 7.430256967974141
accident : 4.815297189937943
accidentally : 7.430256967974141
accomplish : 7.14257489552236
accomplished : 7.14257489552236
accomplishment : 7.430256967974141
accord : 6.91943134420815
according : 5.5331369830882595
account : 5.30999343177405
accountability : 7.14257489552236
accountable : 6.331644679306032
accused : 6.449427714962415
accusing : 7.430256967974141

In [84]:
feature_names = tfidf.get_feature_names_out()
feature_names

array(['abducted', 'ability', 'abject', ..., 'zoo', 'zookeepers',
       'zulyatu'], dtype=object)

In [85]:
print('\nWord indexes:')
print(tfidf.vocabulary_)


Word indexes:
{'really': 3334, 'read': 3324, 'immigrant': 2063, 'article': 246, 'drowned': 1235, 'make': 2500, 'feel': 1538, 'anxious': 180, 'upset': 4341, 'whole': 4500, 'ordeal': 2875, 'happened': 1864, 'terrible': 4078, 'occurrence': 2826, 'happen': 1863, 'mediterranean': 2566, 'sea': 3610, 'thankfully': 4098, 'survivor': 4005, 'fact': 1485, 'baby': 314, 'lost': 2462, 'much': 2689, 'emotional': 1319, 'phone': 3002, 'line': 2420, 'suicide': 3969, 'prevention': 3153, 'election': 1303, 'also': 143, 'climbed': 714, 'williams': 4511, 'committed': 767, 'help': 1928, 'need': 2737, 'thought': 4121, 'condition': 815, 'people': 2972, 'committing': 769, 'permanent': 2984, 'solution': 3801, 'temporary': 4069, 'problem': 3173, 'matter': 2542, 'heritage': 1935, 'able': 3, 'serve': 3655, 'country': 911, 'thai': 4094, 'shouldnt': 3718, 'issue': 2228, 'debate': 1018, 'duckworth': 1243, 'family': 1505, 'service': 3657, 'provided': 3226, 'type': 4271, 'racism': 3286, 'allowed': 133, 'frightening': 16

In [86]:
print('\ntf-idf value:')
print(result)


tf-idf value:
  (0, 1319)	0.2218601236379868
  (0, 2689)	0.12195814495095614
  (0, 2462)	0.16267861344239054
  (0, 314)	0.1956950459795612
  (0, 1485)	0.16219581740318417
  (0, 4005)	0.2491336515969067
  (0, 4098)	0.25902221679407333
  (0, 3610)	0.21579469771681525
  (0, 2566)	0.25902221679407333
  (0, 1863)	0.15028099865599415
  (0, 2826)	0.2650876427152448
  (0, 4078)	0.16032177829263355
  (0, 1864)	0.1528440597616443
  (0, 2875)	0.2650876427152448
  (0, 4500)	0.17194752199790334
  (0, 4341)	0.19245919198713415
  (0, 180)	0.28104163383358305
  (0, 1538)	0.1033355121222132
  (0, 2500)	0.21650637572833337
  (0, 1235)	0.2722615189369107
  (0, 246)	0.09169477036700618
  (0, 2063)	0.22649457791574318
  (0, 3324)	0.20753581060709714
  (0, 3334)	0.09886864658867203
  (1, 3173)	0.1043058547446552
  :	:
  (1858, 1776)	0.13265852936725064
  (1858, 1538)	0.2998693263030751
  (1858, 2500)	0.20942661980904717
  (1859, 3996)	0.22866264210389578
  (1859, 3557)	0.2884966077573959
  (1859, 4479)	0.2

In [87]:
print('\ntf-idf values with word indices:')
feature_names = tfidf.get_feature_names_out()

for i, doc in enumerate(result):
    for j, value in zip(doc.indices, doc.data):
        word = feature_names[j]
        print(f"  (Document {i}, {word}:{j}) TFIDF {value:.4f}")


tf-idf values with word indices:
  (Document 0, emotional:1319) TFIDF 0.2219
  (Document 0, much:2689) TFIDF 0.1220
  (Document 0, lost:2462) TFIDF 0.1627
  (Document 0, baby:314) TFIDF 0.1957
  (Document 0, fact:1485) TFIDF 0.1622
  (Document 0, survivor:4005) TFIDF 0.2491
  (Document 0, thankfully:4098) TFIDF 0.2590
  (Document 0, sea:3610) TFIDF 0.2158
  (Document 0, mediterranean:2566) TFIDF 0.2590
  (Document 0, happen:1863) TFIDF 0.1503
  (Document 0, occurrence:2826) TFIDF 0.2651
  (Document 0, terrible:4078) TFIDF 0.1603
  (Document 0, happened:1864) TFIDF 0.1528
  (Document 0, ordeal:2875) TFIDF 0.2651
  (Document 0, whole:4500) TFIDF 0.1719
  (Document 0, upset:4341) TFIDF 0.1925
  (Document 0, anxious:180) TFIDF 0.2810
  (Document 0, feel:1538) TFIDF 0.1033
  (Document 0, make:2500) TFIDF 0.2165
  (Document 0, drowned:1235) TFIDF 0.2723
  (Document 0, article:246) TFIDF 0.0917
  (Document 0, immigrant:2063) TFIDF 0.2265
  (Document 0, read:3324) TFIDF 0.2075
  (Document 0, 

In [88]:
vectorizer = TfidfVectorizer(ngram_range = (1, 1)) 
tfidf_matrix = vectorizer.fit_transform(gram1data) 
scores = (tfidf_matrix.toarray()) 
print("\n\nScores : \n", scores) 



Scores : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [89]:
sums = tfidf_matrix.sum(axis = 0) 
processing = [] 
for col, term in enumerate(feature_names): 
    processing.append( (term, sums[0, col] )) 
ranking = pd.DataFrame(processing, columns = ['term', 'tfidf'])


words = (ranking.sort_values('tfidf', ascending = False)) 
print ("\n\nWords : \n", words.head(30)) 



Words : 
            term      tfidf
2972     people  75.224417
2414       like  48.953531
246     article  44.658380
4112      think  44.473852
3334     really  42.489161
4560      would  39.925188
1538       feel  38.896431
1201       dont  36.678049
4111      thing  36.123191
2324       know  35.637836
1744        get  35.279800
2848        one  35.078788
2409       life  33.286272
3324       read  32.997858
2500       make  32.776660
911     country  32.667335
2737       need  32.611418
3549        sad  29.781650
902       could  29.499650
1769      going  28.815638
4142       time  27.872584
2522       many  27.471150
4462        way  27.400067
1395       even  27.039836
3809  something  26.909702
668       child  26.785179
4549      world  25.544072
1505     family  25.367388
2689       much  25.238860
572        cant  24.718300


In [91]:
words.to_csv('../data/TFIDF_values_ranking_1gram.csv', sep=';', index=False)

So basically, each row is a document(example text), and each column is a word from the corpus - we have 11 words for now so wooohoooo


Now I'm tryna make the TFIDF for 2gram work

In [107]:
gram2data = data['2-gram']

gram2data

0       ['really read', 'read immigrant', 'immigrant a...
1       ['phone line', 'line suicide', 'suicide preven...
2       ['matter heritage', 'heritage able', 'able ser...
3       ['frightening learn', 'learn shark', 'shark at...
4       ['generation russian', 'russian arent', 'arent...
                              ...                        
1855    ['day woman', 'woman winning', 'winning sport'...
1856    ['hate isi', 'isi group', 'group full', 'full ...
1857    ['disgusting can', 'can not', 'not believe', '...
1858    ['feel like', 'like world', 'world corrupt', '...
1859    ['weird experience', 'experience many', 'many ...
Name: 2-gram, Length: 1860, dtype: object

In [108]:
vectorizer = CountVectorizer(ngram_range=(2,2))
sparse_matrix_gram2data = vectorizer.fit_transform(gram2data)
features = vectorizer.get_feature_names_out()

print("\n\nFeatures: \n", features)



Features: 
 ['abducted abducted' 'abducted killed' 'abducted tortured' ...
 'zulyatu alone' 'zulyatu younger' 'zulyatu zulyatu']


In [109]:
print("\n\n Sparse Matrix : \n", sparse_matrix_gram2data.toarray()) 



 Sparse Matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [110]:
vectorizer = TfidfVectorizer(ngram_range = (2, 2)) 
tfidf_matrix = vectorizer.fit_transform(gram2data) 
scores = (tfidf_matrix.toarray()) 
print("\n\nScores : \n", scores) 



Scores : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [111]:
sums = tfidf_matrix.sum(axis = 0) 
processing = [] 
for col, term in enumerate(features): 
    processing.append( (term, sums[0, col] )) 
    
    
ranking = pd.DataFrame(processing, columns = ['term', 'tfidf'])
pairs2gram = (ranking.sort_values('tfidf', ascending = False)) 
print ("\n\nWords : \n", pairs2gram.head(30)) 



Words : 
                       term      tfidf
36749        people people  42.835236
28917            like like  28.046780
3165       article article  24.250060
50714          think think  23.372148
40861        really really  22.878517
57046          would would  22.875249
17342            feel feel  20.778192
19520              get get  20.438572
50375          thing thing  20.248060
35138              one one  20.066727
13498            dont dont  20.030881
27264            know know  19.978380
30520            make make  18.653850
10403      country country  18.480171
33604            need need  18.384312
28553            life life  18.212399
10142          could could  16.900871
20299          going going  16.144728
51342            time time  15.633910
15513            even even  15.604295
7985           child child  15.511327
30911            many many  15.434556
55016              way way  15.196694
46335  something something  14.965099
42877              sad sad  14.757126


In [112]:
pairs2gram.to_csv('../data/TFIDF_values_ranking_2gram.csv', sep=';', index=False)