In [115]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


Database:

In [79]:
data = pd.read_csv('../data/train_ready_for_WS_preprocessed.csv', delimiter=';', header=0)
data

article_id                                              essay  emotion  \
0             67  really read immigrant article drowned make fee...  sadness   
1             86  phone line suicide prevention line election al...  sadness   
2            206  matter heritage able serve country thai herita...  neutral   
3            290  frightening learn shark attack surfer aware ri...     fear   
4            342  generation russian arent treated properly sort...  sadness   
...          ...                                                ...      ...   
1855          16  day woman winning sport many instance men spor...      joy   
1856         158  hate isi group full hate insanity reason thing...    anger   
1857         203  disgusting can not believe happening people pe...  disgust   
1858         253  feel like world corrupt longer make feel anyth...  sadness   
1859         344  weird experience many people dying enough safe...  sadness   

                                                 tokens  \
0     ['really', 'read', 'immigrant', 'article', 'dr...   
1     ['phone', 'line', 'suicide', 'prevention', 'li...   
2     ['matter', 'heritage', 'able', 'serve', 'count...   
3     ['frightening', 'learn', 'shark', 'attack', 's...   
4     ['generation', 'russian', 'arent', 'treated', ...   
...                                                 ...   
1855  ['day', 'woman', 'winning', 'sport', 'many', '...   
1856  ['hate', 'isi', 'group', 'full', 'hate', 'insa...   
1857  ['disgusting', 'can', 'not', 'believe', 'happe...   
1858  ['feel', 'like', 'world', 'corrupt', 'longer',...   
1859  ['weird', 'experience', 'many', 'people', 'dyi...   

                                                 1-gram  \
0     ['really', 'read', 'immigrant', 'article', 'dr...   
1     ['phone', 'line', 'suicide', 'prevention', 'li...   
2     ['matter', 'heritage', 'able', 'serve', 'count...   
3     ['frightening', 'learn', 'shark', 'attack', 's...   
4     ['generation', 'russian', 'arent', 'treated', ...   
...                                                 ...   
1855  ['day', 'woman', 'winning', 'sport', 'many', '...   
1856  ['hate', 'isi', 'group', 'full', 'hate', 'insa...   
1857  ['disgusting', 'can', 'not', 'believe', 'happe...   
1858  ['feel', 'like', 'world', 'corrupt', 'longer',...   
1859  ['weird', 'experience', 'many', 'people', 'dyi...   

                                                 2-gram  
0     ['really read', 'read immigrant', 'immigrant a...  
1     ['phone line', 'line suicide', 'suicide preven...  
2     ['matter heritage', 'heritage able', 'able ser...  
3     ['frightening learn', 'learn shark', 'shark at...  
4     ['generation russian', 'russian arent', 'arent...  
...                                                 ...  
1855  ['day woman', 'woman winning', 'winning sport'...  
1856  ['hate isi', 'isi group', 'group full', 'full ...  
1857  ['disgusting can', 'can not', 'not believe', '...  
1858  ['feel like', 'like world', 'world corrupt', '...  
1859  ['weird experience', 'experience many', 'many ...  

[1860 rows x 6 columns]

TF-IDF

There are multiple ways to calculate the TF(term frequency)

IDF - inverse document frequency
- looks ar common/uncommon words - corrects for words like as, of, the etc
- minimize the weighting of frequent terms while making infrequent terms have a higher impact.


And then I discovered that you can do all these using TfidfVectorizer that basically does everything you need

In [117]:
gram1data = data['1-gram'].head(5)

gram1data

0    ['really', 'read', 'immigrant', 'article', 'dr...
1    ['phone', 'line', 'suicide', 'prevention', 'li...
2    ['matter', 'heritage', 'able', 'serve', 'count...
3    ['frightening', 'learn', 'shark', 'attack', 's...
4    ['generation', 'russian', 'arent', 'treated', ...
Name: 1-gram, dtype: object

In [118]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(gram1data)

result

<5x112 sparse matrix of type '<class 'numpy.float64'>'
	with 115 stored elements in Compressed Sparse Row format>

In [119]:
feature_names = tfidf.get_feature_names_out()

print('\nIDF values:')
for ele1, ele2 in zip(feature_names, tfidf.idf_):
    print(ele1, ':', ele2)


IDF values:
able : 2.09861228866811
afford : 2.09861228866811
allowed : 2.09861228866811
also : 1.6931471805599454
anxious : 2.09861228866811
arent : 2.09861228866811
article : 2.09861228866811
associated : 2.09861228866811
attack : 2.09861228866811
australia : 2.09861228866811
aware : 2.09861228866811
baby : 2.09861228866811
barely : 2.09861228866811
beach : 2.09861228866811
best : 2.09861228866811
cant : 2.09861228866811
care : 2.09861228866811
climbed : 2.09861228866811
committed : 2.09861228866811
committing : 2.09861228866811
condition : 1.6931471805599454
cost : 2.09861228866811
country : 2.09861228866811
day : 2.09861228866811
dealt : 2.09861228866811
debate : 2.09861228866811
drowned : 2.09861228866811
duckworth : 2.09861228866811
due : 2.09861228866811
election : 2.09861228866811
emotional : 2.09861228866811
enough : 2.09861228866811
epidemic : 2.09861228866811
establish : 2.09861228866811
fact : 2.09861228866811
family : 2.09861228866811
feel : 2.09861228866811
financial : 2

In [120]:
feature_names = tfidf.get_feature_names_out()
feature_names

array(['able', 'afford', 'allowed', 'also', 'anxious', 'arent', 'article',
       'associated', 'attack', 'australia', 'aware', 'baby', 'barely',
       'beach', 'best', 'cant', 'care', 'climbed', 'committed',
       'committing', 'condition', 'cost', 'country', 'day', 'dealt',
       'debate', 'drowned', 'duckworth', 'due', 'election', 'emotional',
       'enough', 'epidemic', 'establish', 'fact', 'family', 'feel',
       'financial', 'financially', 'food', 'frightening', 'generation',
       'get', 'good', 'happen', 'happened', 'health', 'help', 'heritage',
       'immigrant', 'interest', 'involved', 'issue', 'learn', 'line',
       'little', 'live', 'living', 'lost', 'make', 'matter',
       'mediterranean', 'method', 'much', 'need', 'occurrence', 'ordeal',
       'paying', 'people', 'per', 'permanent', 'phone', 'poor',
       'precautionary', 'prevention', 'priority', 'problem', 'proper',
       'properly', 'provided', 'racism', 'read', 'really', 'risk',
       'russian', 'sea', 's

In [121]:
print('\nWord indexes:')
print(tfidf.vocabulary_)


Word indexes:
{'really': 82, 'read': 81, 'immigrant': 49, 'article': 6, 'drowned': 26, 'make': 59, 'feel': 36, 'anxious': 4, 'upset': 106, 'whole': 108, 'ordeal': 66, 'happened': 45, 'terrible': 98, 'occurrence': 65, 'happen': 44, 'mediterranean': 61, 'sea': 85, 'thankfully': 100, 'survivor': 95, 'fact': 34, 'baby': 11, 'lost': 58, 'much': 63, 'emotional': 30, 'phone': 71, 'line': 54, 'suicide': 93, 'prevention': 74, 'election': 29, 'also': 3, 'climbed': 17, 'williams': 109, 'committed': 18, 'help': 47, 'need': 64, 'thought': 101, 'condition': 20, 'people': 68, 'committing': 19, 'permanent': 70, 'solution': 90, 'temporary': 97, 'problem': 76, 'matter': 60, 'heritage': 48, 'able': 0, 'serve': 86, 'country': 22, 'thai': 99, 'shouldnt': 89, 'issue': 52, 'debate': 25, 'duckworth': 27, 'family': 35, 'service': 87, 'provided': 79, 'type': 105, 'racism': 80, 'allowed': 2, 'frightening': 40, 'learn': 53, 'shark': 88, 'attack': 8, 'surfer': 94, 'aware': 10, 'risk': 83, 'associated': 7, 'sport'

In [122]:
print('\ntf-idf value:')
print(result)


tf-idf value:
  (0, 30)	0.1836457753647447
  (0, 63)	0.1836457753647447
  (0, 58)	0.1836457753647447
  (0, 11)	0.1836457753647447
  (0, 34)	0.1836457753647447
  (0, 95)	0.1836457753647447
  (0, 100)	0.14816425523644533
  (0, 85)	0.1836457753647447
  (0, 61)	0.1836457753647447
  (0, 44)	0.1836457753647447
  (0, 65)	0.1836457753647447
  (0, 98)	0.1836457753647447
  (0, 45)	0.1836457753647447
  (0, 66)	0.1836457753647447
  (0, 108)	0.1836457753647447
  (0, 106)	0.1836457753647447
  (0, 4)	0.1836457753647447
  (0, 36)	0.1836457753647447
  (0, 59)	0.3672915507294894
  (0, 26)	0.1836457753647447
  (0, 6)	0.1836457753647447
  (0, 49)	0.1836457753647447
  (0, 81)	0.3672915507294894
  (0, 82)	0.1836457753647447
  (1, 76)	0.1742024183731
  :	:
  (4, 110)	0.16830668925257494
  (4, 104)	0.16830668925257494
  (4, 96)	0.16830668925257494
  (4, 16)	0.16830668925257494
  (4, 46)	0.3366133785051499
  (4, 39)	0.16830668925257494
  (4, 31)	0.16830668925257494
  (4, 12)	0.16830668925257494
  (4, 67)	0.16

In [123]:
print('\ntf-idf values with word indices:')
feature_names = tfidf.get_feature_names_out()

for i, doc in enumerate(result):
    for j, value in zip(doc.indices, doc.data):
        word = feature_names[j]
        print(f"  (Document {i}, {word}:{j}) TFIDF {value:.4f}")


tf-idf values with word indices:
  (Document 0, emotional:30) TFIDF 0.1836
  (Document 0, much:63) TFIDF 0.1836
  (Document 0, lost:58) TFIDF 0.1836
  (Document 0, baby:11) TFIDF 0.1836
  (Document 0, fact:34) TFIDF 0.1836
  (Document 0, survivor:95) TFIDF 0.1836
  (Document 0, thankfully:100) TFIDF 0.1482
  (Document 0, sea:85) TFIDF 0.1836
  (Document 0, mediterranean:61) TFIDF 0.1836
  (Document 0, happen:44) TFIDF 0.1836
  (Document 0, occurrence:65) TFIDF 0.1836
  (Document 0, terrible:98) TFIDF 0.1836
  (Document 0, happened:45) TFIDF 0.1836
  (Document 0, ordeal:66) TFIDF 0.1836
  (Document 0, whole:108) TFIDF 0.1836
  (Document 0, upset:106) TFIDF 0.1836
  (Document 0, anxious:4) TFIDF 0.1836
  (Document 0, feel:36) TFIDF 0.1836
  (Document 0, make:59) TFIDF 0.3673
  (Document 0, drowned:26) TFIDF 0.1836
  (Document 0, article:6) TFIDF 0.1836
  (Document 0, immigrant:49) TFIDF 0.1836
  (Document 0, read:81) TFIDF 0.3673
  (Document 0, really:82) TFIDF 0.1836
  (Document 1, pro

In [124]:
vectorizer = TfidfVectorizer(ngram_range = (1, 1)) 
tfidf_matrix = vectorizer.fit_transform(gram1data) 
scores = (tfidf_matrix.toarray()) 
print("\n\nScores : \n", scores) 



Scores : 
 [[0.         0.         0.         0.         0.18364578 0.
  0.18364578 0.         0.         0.         0.         0.18364578
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.18364578 0.         0.         0.
  0.18364578 0.         0.         0.         0.18364578 0.
  0.18364578 0.         0.         0.         0.         0.
  0.         0.         0.18364578 0.18364578 0.         0.
  0.         0.18364578 0.         0.         0.         0.
  0.         0.         0.         0.         0.18364578 0.36729155
  0.         0.18364578 0.         0.18364578 0.         0.18364578
  0.18364578 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.36729155 0.18364578 0.
  0.         0.18364578 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.1836

In [125]:
sums = tfidf_matrix.sum(axis = 0) 
processing = [] 
for col, term in enumerate(feature_names): 
    processing.append( (term, sums[0, col] )) 
ranking = pd.DataFrame(processing, columns = ['term', 'tfidf'])


words = (ranking.sort_values('tfidf', ascending = False)) 
print ("\n\nWords : \n", words.head(30)) 



Words : 
            term     tfidf
54         line  0.522607
88        shark  0.522233
89     shouldnt  0.377964
25       debate  0.377964
48     heritage  0.377964
22      country  0.377964
81         read  0.367292
59         make  0.367292
64         need  0.348405
74   prevention  0.348405
92        sport  0.348155
46       health  0.336613
100  thankfully  0.288710
3          also  0.276334
20    condition  0.276334
60       matter  0.188982
80       racism  0.188982
79     provided  0.188982
86        serve  0.188982
87      service  0.188982
35       family  0.188982
52        issue  0.188982
27    duckworth  0.188982
0          able  0.188982
2       allowed  0.188982
105        type  0.188982
99         thai  0.188982
45     happened  0.183646
82       really  0.183646
65   occurrence  0.183646


In [91]:
words.to_csv('../data/TFIDF_values_ranking_1gram.csv', sep=';', index=False)

So basically, each row is a document(example text), and each column is a word from the corpus - we have 11 words for now so wooohoooo


Now I'm tryna make the TFIDF for 2gram work

In [161]:
gram2data = data['essay']
gram2data

0       really read immigrant article drowned make fee...
1       phone line suicide prevention line election al...
2       matter heritage able serve country thai herita...
3       frightening learn shark attack surfer aware ri...
4       generation russian arent treated properly sort...
                              ...                        
1855    day woman winning sport many instance men spor...
1856    hate isi group full hate insanity reason thing...
1857    disgusting can not believe happening people pe...
1858    feel like world corrupt longer make feel anyth...
1859    weird experience many people dying enough safe...
Name: essay, Length: 1860, dtype: object

In [171]:
vectorizer = CountVectorizer(ngram_range=(2,2))
sparse_matrix_gram2data = vectorizer.fit_transform(gram2data)
sparse_matrix_gram2data
features = vectorizer.get_feature_names_out()


print("\n\nFeatures: \n", features)



Features: 
 ['abducted killed' 'abducted tortured' 'ability able' ...
 'zookeepers shoot' 'zulyatu alone' 'zulyatu younger']


In [168]:
print("\n\n Sparse Matrix : \n", sparse_matrix_gram2data.toarray()) 



 Sparse Matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [172]:
vectorizer = TfidfVectorizer(ngram_range = (2, 2)) 
tfidf_matrix = vectorizer.fit_transform(gram2data) 
scores = (tfidf_matrix.toarray()) 
print("\n\nScores : \n", scores) 



Scores : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [173]:
sums = tfidf_matrix.sum(axis = 0) 
processing = [] 
for col, term in enumerate(features): 
    processing.append( (term, sums[0, col] )) 
    
    
ranking = pd.DataFrame(processing, columns = ['term', 'tfidf'])
pairs2gram = (ranking.sort_values('tfidf', ascending = False)) 
print ("\n\nWords : \n", pairs2gram.head(30)) 



Words : 
                   term      tfidf
37144     read article  11.900401
15891        feel like   8.099647
7836    climate change   7.755460
28499      many people   7.344824
15819         feel bad   7.298333
6219           can not   6.543351
40561       seems like   6.419565
12369        dont know   6.296486
22424          im sure   5.632561
3158      article read   5.496051
12415       dont think   5.163374
37318  reading article   4.566770
6278      cant believe   4.526481
29395      middle east   4.516918
6314      cant imagine   4.351114
42616   something like   4.323222
12222     donald trump   4.251266
18286   global warming   4.222920
12419  dont understand   4.211120
49118     united state   4.160152
28079        make feel   3.949001
37650       really sad   3.854407
22369          im glad   3.788906
42907       sound like   3.755581
46308       thing like   3.690122
34990   police officer   3.684888
34093     people would   3.462663
15951       feel sorry   3.355404
28

In [174]:
pairs2gram.to_csv('../data/TFIDF_values_ranking_2gram.csv', sep=';', index=False)